mindmap/urls.py
# coding: utf-8
from django.conf.urls import url
from mindmap.views import views_common, views_index, views_mind, views_category, views_user, views_tag
from mindmap.views import views_feedback


urlpatterns = [
    url(r'^$', views_index.index, name='index'),
    url(r'^page/(?P<page>\d+)?$', views_index.index, name='index-without-category'),
    url(r'^category/(?P<category>\d+)/page/(?P<page>\d+)?$', views_index.index, name='index-with-category'),

    # Mind
    url(r'new-mind-page/?', views_mind.mind_new, name='new-mind-page'),
    url(r'new-mind/?', views_mind.process_new_mind, name='new-mind'),
    url(r'mind/delete/?', views_mind.delete_mind, name='mind-delete'),
    url(r'mind/vote/?', views_mind.mind_vote, name='mind-vote'),
    url(r'mind/show/(?P<tid>\d+)?/?', views_mind.show_mind_detail, name='show-mind'),

    # tag
    url(r'mind/tag/(?P<tid>\d+)/page/(?P<page>\d+)?/?', views_tag.show_tag_page, name='mind-tag-page'),

    # 关于
    url(r'about/?', views_common.about_view, name='about'),

    # 反馈
    url(r'feedback/add/?', views_feedback.feedback_add, name='feedback-add'),
]

# 分类
urlpatterns += [
    url(r'category/show/?', views_category.show_category, name='category-show'),
]

# 用户相关url
urlpatterns += [
    # 用户书单列表
    url(r'^user/register/?$', views_user.user_register, name='register'),
    url(r'^user/login/?$', views_user.user_login, name='login'),
    url(r'^user/logout/?$', views_user.user_logout, name='logout'),
    url(r'^user/profile/?$', views_user.user_profile, name='user-profile'),
    url(r'^user/profile/update/?$', views_user.user_profile_update, name='user-profile-update'),
    url(r'^user/page/(?P<page>\d+)/?$', views_user.user_page, name='user-page'),
    url(r'^user/(?P<uid>\d+)/page/(?P<page>\d+)/?$', views_user.user_page, name='user-page-with-uid')
]

# 最后
urlpatterns += [
    # 如果都没有匹配, 返回404页面
    url(r'', views_common.return_404_page, name='404-page'),
]


mindshare/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from mindshare import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mindmap.urls', namespace='mindmap')),
]

mindmap/views/url_generator.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: url_generator.py
DATE: 17-7-31 下午5:07
DESC: 
"""
from django.urls import reverse


def index_url_generator(page=1, category=None, **kwargs):
    if category is not None:
        return reverse('mindmap:index-with-category', args=(category, page))
    else:
        return reverse('mindmap:index-without-category', args=(page, ))


def user_page_pagination_url_generator(page=1, uid=None, *args, **kwargs):
    if uid is not None:
        return reverse('mindmap:user-page', args=(page,))
    else:
        return reverse('mindmap:user-page-with-uid', args=(uid, page))


def tag_url_generator(page=1, tid=None, **kwargs):
    return reverse('mindmap:mind-tag-page', args=(tid, page))

mindmap/views/views_category.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_category.py
DATE: 17-7-28 下午12:21
DESC: 
"""
import traceback

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from mindmap.models import Category, MindMap
from mindmap.views.views_common import return_404_page


@csrf_exempt
def show_category(request):
    """获取所有分类"""
    return JsonResponse({'categorys': [v.convert_to_dict() for v in Category.objects.all()]})


# def show_category_page(request, cid):
#     try:
#         category = Category.objects.filter(id=cid).first()
#         items = MindMap.objects.filter(category_id=cid).order_by('-vote')
#
#         context = {
#             'title': '分类 - ' + category.title
#         }
#     except Exception as e:
#         print(e)
#         traceback.print_exc()
#     return return_404_page(request)

mindmap/views/views_common.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_common.py
DATE: 17-7-27 下午12:29
DESC: 
"""
from django.shortcuts import render

from mindmap.models import Article


def return_404_page(request):
    return render(request, 'mindmap/404page.html')


def json_res(res=False, msg=None, data=None, **kwargs):
    res_dict = {
        'res': 'success' if res else 'error',
        'msg': '操作成功' if res else '未知错误',
        'data': data
    }
    res_dict.update(kwargs)

    if msg:
        res_dict['msg'] = msg
    return res_dict


def about_view(request):
    article = Article.objects.filter(title='about').first() or Article.objects.filter(title='关于').first()    # 获取

    context = {
        'title': '关于',
        'article': article
    }

    return render(request, 'mindmap/html/markdown-show.html', context=context)

mindmap/views/views_feedback.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_feedback.py
DATE: 17-10-26 上午9:04
DESC: 用户反馈视图
"""
import traceback

from django.http import JsonResponse

from mindmap.models import FeedbackMessage
from mindmap.views.views_common import json_res


def feedback_add(request):
    """添加反馈
    POST 方法，Json格式
    POST 内容：
        content: 反馈内容
    """
    try:
        # feedback = FeedbackMessage(content=request.POST.get('content'),
        #                            user_id=request.user.id if request.user.is_authenticated() else None)
        feedback = FeedbackMessage(content=request.POST.get('content'),
                                   user=request.user if request.user.is_authenticated() else None)
        feedback.save()
        return JsonResponse(json_res(res=True))
    except Exception as e:
        print(e)
        traceback.print_exc()
        return JsonResponse(json_res(res=False, msg=str(e)))

mindmap/views/views_index.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_index.py
DATE: 17-7-27 下午12:28
DESC: 
"""
import traceback

from django.shortcuts import render

from mindmap.models import Category, MindMap
from mindmap.views.url_generator import index_url_generator
from mindmap.views.views_common import return_404_page
from mindmap.views.views_pagination import get_pages


def index(request, category=None, page=1):
    try:
        cur_category = None
        category_first = None
        category_second = None

        if category is not None:
            cur_category = Category.objects.filter(id=category).first()
            items = (MindMap.objects.filter(category_id=category, public=True) |
                     MindMap.objects.filter(category__parent=category, public=True))
        else:
            items = MindMap.objects.filter(public=True)

        # 排序
        order = request.GET.get('ord')
        if order is None or order == 'hot':
            order = 'hot'
            items = items.order_by('-vote', '-create_date')
        elif order == 'new':
            items = items.order_by('-create_date', '-vote')

        if cur_category:
            # 如果有当前分类
            if cur_category.parent:
                # 如果当前节点有父节点
                category_first = cur_category.parent
                category_second = cur_category
                category_second_items = Category.objects.filter(parent=cur_category.parent)
            else:
                category_first = cur_category
                category_second = None
                category_second_items = Category.objects.filter(parent=cur_category)
        else:
            category_second_items = Category.objects.filter(parent__isnull=False)[:12]
        context = {
            'title': 'MindShare',
            'category_first': category_first,
            'category_second': category_second,
            'category_first_items': Category.objects.filter(parent__isnull=True),
            'category_second_items': category_second_items,
            'pages': get_pages(items, cur_page=page, url_generator=index_url_generator, category=category),
            'category': category,
            'order': order
        }

        return render(request, 'mindmap/index.html', context=context)
    except Exception as e:
        print(e)
        traceback.print_exc()
        return return_404_page(request)

mindmap/views/views_mind.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_mind.py
DATE: 17-7-27 下午5:44
DESC: 
"""
import re
import traceback

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from mindmap.forms import MindMapForm
from mindmap.models import Category, Tag, MindMap, MindMapVote
from mindmap.views.views_common import json_res, return_404_page


@login_required
def mind_new(request):
    context = {
        'title': '创建主题',
        'category_first': Category.objects.filter(parent__isnull=True)
    }
    return render(request, 'mindmap/mind-new.html', context=context)


@login_required
def process_new_mind(request):
    try:
        form = MindMapForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            # 验证成功
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            # 处理信息
            try:
                # 添加标签
                tags_str = request.POST.get('tags')
                if tags_str:
                    tags = re.split(r'[,，]', tags_str)
                    for tag in tags:
                        tag = str(tag).strip()
                        if len(tag) == 0:
                            continue
                        tag_instance = Tag.objects.filter(title=tag).first()
                        if not tag_instance:
                            tag_instance = Tag(title=tag)
                        tag_instance.cnt += 1
                        tag_instance.save()

                        instance.tags.add(tag_instance)
            except Exception as e:
                print(e)
                traceback.print_exc()
            return JsonResponse(json_res(res=True))
        else:
            # 验证失败
            # 获取错误信息
            msg = [(k, v[0]) for k, v in form.errors.items()]
            return JsonResponse(json_res(res=False, msg=msg))
    except Exception as e:
        print(e)
        traceback.print_exc()
    return JsonResponse(json_res())


def show_mind_detail(request, tid=None):
    try:
        if tid:
            context = {}
            mindmap = MindMap.objects.filter(id=tid, public=True).first()
            if mindmap:
                if request.user.is_authenticated and \
                        MindMapVote.objects.filter(mindmap=mindmap, author=request.user).exists():
                    context['voted'] = True
                else:
                    context['voted'] = False
                context['title'] = mindmap.title
                context['mindmap'] = mindmap
                return render(request, 'mindmap/mind-detail.html', context=context)
    except Exception as e:
        print(e)
        traceback.print_exc()
    return return_404_page(request)


@login_required
@require_http_methods(["POST"])
def delete_mind(request):
    try:
        mindmap_id = request.POST.get('id')
        mindmap = MindMap.objects.filter(id=mindmap_id, public=True).first()
        if mindmap is not None:
            if mindmap.author != request.user and not request.user.is_superuser:
                return JsonResponse(json_res(res=False, msg='不是该导图创建用户无法删除'))
            else:
                mindmap.public = False
                mindmap.save()
                return JsonResponse(json_res(res=True))
        else:
            return JsonResponse(json_res(res=False, msg='思维导图不存在'))
    except Exception as e:
        print(e)
        traceback.print_exc()
    return JsonResponse(json_res(res=False, msg='未知错误'))


@login_required
@require_http_methods(["POST"])
def mind_vote(request):
    try:
        mindmap_id = request.POST.get('id')
        mindmap = MindMap.objects.filter(id=mindmap_id, public=True).first()
        if mindmap is not None:
            if not request.user.is_authenticated:
                return JsonResponse(json_res(res=False, msg='未登录', action='login'))
            else:
                mindmap_vote = MindMapVote.objects.filter(author=request.user, mindmap=mindmap).first()
                print(mindmap_vote)
                if mindmap_vote is not None:
                    mindmap_vote.delete()
                    mindmap.vote -= max(0, mindmap.vote)
                    mindmap.save()
                    return JsonResponse(json_res(res=True, action='devote', vote=mindmap.vote))
                else:
                    mindmap_vote = MindMapVote(author=request.user, mindmap=mindmap)
                    mindmap_vote.save()
                    mindmap.vote += 1
                    mindmap.save()
                    return JsonResponse(json_res(res=True, action='vote', vote=mindmap.vote))
        else:
            return JsonResponse(json_res(res=False, msg='思维导图不存在'))
    except Exception as e:
        print(e)
        traceback.print_exc()
    return JsonResponse(json_res(res=False, msg='未知错误'))

mindmap/views/views_pagination.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_pagination.py
DATE: 17-7-31 下午12:25
DESC: 自定义分页工具
"""
import traceback

from django.core.paginator import Paginator

from mindshare.settings import COUNT_PER_PAGE


class PageItem:
    def __init__(self, url='javascript: void(0)', number=1, text=None, active=True):
        self.url = url
        self.number = number
        self.text = text if text is not None else number
        self.active = active


class PageInstance:
    def __init__(self, total_page_number, cur_page_number, cur_page_items, url_generator=None, **kwargs):
        # 所有分页
        self.total_page_number = total_page_number
        # 当前分页
        self.cur_page_number = cur_page_number
        # 当前分页记录
        self.cur_page_items = cur_page_items
        # url 生成器
        self.url_generator = url_generator
        self.kwargs = kwargs
        # 分页列表项目
        self.page_items = []
        self.init_page_items()

    def init_page_items(self):
        _page_items_number = {1, self.total_page_number}
        for i in range(max(1, self.cur_page_number-3), min(self.cur_page_number+3, self.total_page_number)):
            _page_items_number.add(i)
        for page_number in _page_items_number:
            if len(self.page_items) > 0 and self.page_items[-1].number and page_number - self.page_items[-1].number > 1:
                self.page_items.append(PageItem(text='...', active=False))

            if page_number == self.cur_page_number:
                self.page_items.append(PageItem(number=page_number, active=False))
            elif self.url_generator:
                self.page_items.append(PageItem(url=self.url_generator(page_number, **self.kwargs), number=page_number))
            else:
                self.page_items.append(PageItem(number=page_number))


def get_pages(query_set, cur_page=1, count_per_page=COUNT_PER_PAGE, url_generator=None, **kwargs):
    """
    获取供模板使用的分页信息
    :param url_generator:
    :param query_set: model query set
    :param cur_page: 当前页码
    :param count_per_page: 每页记录数
    :return:
    """
    try:
        cur_page = int(cur_page) if cur_page else 1
        page_list = Paginator(query_set, count_per_page)
        total_page_number = page_list.num_pages
        cur_page_number = max(0, min(cur_page, total_page_number))
        cur_page_items = page_list.page(cur_page_number)
        return PageInstance(total_page_number, cur_page_number, cur_page_items, url_generator, **kwargs)
    except Exception as e:
        print(e)
        traceback.print_exc()
        return PageInstance(0, 0, None)

mindmap/views/views_tag.py
#!/usr/bin python3
# coding: utf-8

"""
AUTHOR: bovenson
EMAIL: szhkai@qq.com
FILE: views_tag.py
DATE: 17-8-1 上午11:23
DESC: 
"""
import traceback

from django.shortcuts import render

from mindmap.models import Tag, MindMap
from mindmap.views.url_generator import tag_url_generator
from mindmap.views.views_common import return_404_page
from mindmap.views.views_pagination import get_pages


def show_tag_page(request, tid, page=1):
    try:
        tag = Tag.objects.filter(id=tid).first()
        items = MindMap.objects.filter(tags__in=[tag]).order_by('-vote')
        print(items)

        context = {
            'title': '分类 - ' + tag.title,
            'items': items,
            'tag': tag,
            'pages': get_pages(items, cur_page=page, url_generator=tag_url_generator, tid=tid),
        }
        return render(request, 'mindmap/mind-tag.html', context)
    except Exception as e:
        print(e)
        traceback.print_exc()
    return return_404_page(request)

templates/mindmap/includes/_footer.html
<div id="footer">
    <div class="container">
        <p>FOOTER</p>
    </div>
</div>

templates/mindmap/includes/_index_list_item.html
{# 首页列表项 #}

<div class="container-box-item container-box-item-bottom" id="divMindmap{{ mindmap.id }}">
    <a href="javascript: void(0)" title="投票" class="ol-badge" style="vertical-align: top;">{{ mindmap.vote }}</a>
    <a class="my-title my-title-a" style="margin-bottom: .6rem;" href="{% url 'mindmap:show-mind' mindmap.id %}">
        <span>{{ mindmap.title }}</span>
    </a>
    {% include 'mindmap/includes/_mind_info_panel.html' %}
</div>

templates/mindmap/includes/_login_register.html
{# 登录注册模态框 #}

<div class="modal fade" id="loginRegisterModelBox" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="exampleModalLabel">邮箱登录 / 注册</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="padding: 0 1rem 1.5rem 1rem; width: 80%; margin: auto;">
                <!-- 错误提示 -->
                <div style="padding-left: 0.1rem; height: 1.5rem;">
                    <label id="lrModalErrorTipElement" style="color: red; font-size: .8rem;"></label>
                </div>
                <form>
                    {% csrf_token %}
                    <div class="form-group" style="margin-bottom: .2rem;">
                        <input type="text" class="form-control" id="inputEmail" placeholder="邮箱">
                        <div class="clearfix" style="height: 1rem;"></div>
                        <input type="password" class="form-control" id="inputPassword" placeholder="密码">
                    </div>
                </form>
                <div class="tip-a" style="margin-bottom: 1rem; padding-left: 0.2rem;">
                    <a id="registerOrLoginTipElement" href="javascript: void(0);">还没有账号,点击注册</a>
                </div>
                <div class="text-center register-btn">
                    <a id="registerOrLoginBtnElement" href="javascript: void(0);" style="padding: 0.3rem 3rem; width: 100%; display: inline-block;">登录</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/mindmap/includes/_mind_info_panel.html
{# mind info panel #}

<div class="info-panel">
    <a class="info-panel-item a-tag-light" title="查看分类" href="{% url 'mindmap:index-with-category' mindmap.category.id %}">{{ mindmap.category.title }}</a>
    <span class="info-panel-item">•</span>
    <a class="info-panel-item" title="用户主页" href="{% url 'mindmap:user-page-with-uid' mindmap.author.id 1 %}" style="font-weight: 600;">{{ mindmap.author.nickname}}</a>
    <span class="info-panel-item">•</span>
    <span class="info-panel-item">{{ mindmap.create_date|date:'H:i:s d-m-y' }}</span>
    {% if mindmap.share %}
        <span class="info-panel-item">•</span>
        <a href="{{ mindmap.share }}" title="查看分享" target="_blank" class="info-panel-item"><i class="fa fa-share-alt color-mid-grey" aria-hidden="true"></i></a>
    {% endif %}

    {# 下载 #}
    {% if mindmap.img %}
        <span class="info-panel-item">•</span>
        <a href="{{ mindmap.img.url }}" download="" title="下载图片" class="info-panel-item"><i class="fa fa-picture-o color-mid-grey" aria-hidden="true"></i></a>
    {% endif %}
    {% if mindmap.mindmap %}
        <span class="info-panel-item">•</span>
        <a href="{{ mindmap.mindmap.url }}" download="" title="下载文件" class="info-panel-item"><i class="fa fa-download color-mid-grey" style="margin-top: .05rem;" aria-hidden="true"></i></a>
    {% endif %}

    {% if mindmap.author == request.user or request.user.is_superuser %}
        <span class="info-panel-item">•</span>
        <a href="javascript: deleteMindmap({{ mindmap.id }});" title="删除" class="info-panel-item"><i class="fa fa-trash-o color-mid-grey" aria-hidden="true"></i></a>
    {% endif %}
</div>

templates/mindmap/includes/_navigation.html
{# 导航栏 #}
{% load staticfiles %}

<nav id="navbar">
    <div id="navbarContainer" class="container">
        <div id="brand">
            <img id="brandImg" src="{% static 'mindmap/img/favicon.png' %}"/>
            <a href="{% url 'mindmap:index' %}">MindShare</a>
        </div>
        <div id="linkList">
            <a class="my-nav-link hidden-md-down" href="{% url 'mindmap:index' %}">首页</a>
            {% if request.user.id %}
                {# 引入用户信息弹出框 #}
                {% include 'mindmap/includes/dialog/_popover_user.html' %}
                <a class="my-nav-link" href="{% url 'mindmap:new-mind-page' %}">发布</a>
                <a id="usernameElement" class="my-nav-link" href="javascript: void(0);">{{ request.user.nickname }}</a>
            {% else %}
                <a id="btn-login" class="my-nav-link" href="javascript: void(0);">登录</a>
            {% endif %}
        </div>
    </div>
</nav>
<div class="nav-shadow"></div>

{# 引入登录/注册模态框 #}
{% include 'mindmap/includes/_login_register.html' %}

templates/mindmap/includes/_pagination.html
{# 分页 #}

<div class="page-panel">
    {% for page in pages.page_items %}
        <a class="page-panel-item" {% if page.active %}href="{{ page.url }}"{% endif %}>{{ page.text }}</a>
{#        <a class="page-panel-item" {% if page.active %}href="{% url 'mindmap:index-with-category' category page.number %}"{% endif %}>{{ page.text }}</a>#}
    {% endfor %}
</div>

templates/mindmap/includes/_right_bottom_btn_group.html
{# 左下角按钮组 #}
{% load staticfiles %}

<style>
    .right-bottom-btn-group {
        position: fixed;
        right: 1.2rem;
        bottom: 1.2rem;

        float: left;

        z-index: 1000;
        -webkit-transition: all .5s;
        -moz-transition: all .5s;
        -o-transition: all .5s;
        transition: all .5s;
    }

    .right-bottom-btn-group a {
        width: 2rem;
        height: 1.8rem;

        text-align: center;

        font-size: 0.7rem;
        background: #e7eaf1;
        border-radius: .3rem;
        cursor: pointer;
        margin-top: 0.4rem;

        padding: .3rem;

        float: left;
        clear: both;
    }
</style>

{# 右下角按钮组 #}
<div class="right-bottom-btn-group" id="right-bottom-btn-group">
    <a id="btn-go-top" title="返回顶部"><i class="fa fa-arrow-up fa-2x" aria-hidden="true" style="color: #a1afc8;"></i></a>
    <a href="javascript: feedbackBtnClick();" title="反馈"><i class="fa fa-pencil-square-o fa-2x" aria-hidden="true" style="color: #a1afc8;"></i></a>
    <a href="{% url 'mindmap:about' %}" title="关于"><i class="fa fa-info fa-2x" aria-hidden="true" style="color: #a1afc8;"></i></a>
</div>

{# 反馈 #}
{% include 'mindmap/includes/dialog/_feedback_dialog.html' %}

<script>
{#    // 监听滚动#}
{#    window.onscroll = function(){#}
{#        //获取距离页面顶部的距离#}
{#         var t = document.documentElement.scrollTop || document.body.scrollTop;#}
{#         //获取div元素#}
{#         var rightBottomBtnGroupElement = document.getElementById( "btn-go-top" );#}
{#         rightBottomBtnGroupElement.style.display = 'block';#}
{#         if( t >= 300 ) { //当距离顶部超过300px时#}
{#            rightBottomBtnGroupElement.style.bottom=20+'px';//使div距离底部30px，也就是向上出现#}
{#         } else { //如果距离顶部小于300px#}
{#            rightBottomBtnGroupElement.style.bottom=-50+'px';//使div向下隐藏#}
{#         }#}
{#    };#}
    var goTop = document.getElementById("btn-go-top");
    var timer=null;
    goTop.onclick = function(){ //点击图片时触发点击事件
            timer=setInterval(function(){ //设置一个计时器
            var ct = document.documentElement.scrollTop || document.body.scrollTop; //获取距离顶部的距离
            ct = ct * 0.95;
            if(ct < 5){
                 window.scrollTo(0,0);//移动到顶部
                 clearInterval(timer);//清除计时器
            }
            else{
                 window.scrollTo(0, ct); //向上移动
            }
        }, 10);//隔10ms执行一次前面的function，展现一种平滑滑动效果
    }
</script>

templates/mindmap/includes/base.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    {# 设置图标 #}
    <link href="{% static 'mindmap/img/favicon.png' %}" rel="bookmark" type="image/x-icon" />
    <link href="{% static 'mindmap/img/favicon.png' %}" rel="icon" type="image/x-icon" />
    <link href="{% static 'mindmap/img/favicon.png' %}" rel="shortcut icon" type="image/x-icon" />

    {# 引入公用静态css文件 #}
    <link rel="stylesheet" href="{% static 'mindmap/lib/css/bootstrap-4.0.0-alpha.6.css' %}">
    <link rel="stylesheet" href="{% static 'mindmap/lib/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'mindmap/lib/css/toastr.css' %}">
    <link rel="stylesheet" href="{% static 'mindmap/css/common.css' %}">
    <link rel="stylesheet" href="{% static 'mindmap/css/login-register.css' %}">
    <link rel="stylesheet" href="{% static 'mindmap/css/user-menu-popover.css' %}">

    {# 设置页面自定义css #}
    {% block css %}{% endblock %}
</head>
<body>
    {# 导航栏 #}
    {% block navigation %}
        {% include "mindmap/includes/_navigation.html" %}
    {% endblock %}

    {# body #}
    {% block body %}{% endblock %}

    {# 左下角按钮组 #}
    {% block right-bottom-btn-group %}
        {% include "mindmap/includes/_right_bottom_btn_group.html" %}
    {% endblock %}

    {% include "mindmap/includes/dialog/_confirm_cancel_modal.html" %}

    {# 自定义js #}
    {% block js %}
    {# 加载requirejs #}
        <script src="{% static 'mindmap/lib/js/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'mindmap/lib/js/tether.min.js' %}"></script>
        <script src="{% static 'mindmap/lib/js/bootstrap-4.0.0-alpha.6.js' %}"></script>
        <script src="{% static 'mindmap/lib/js/jquery.cookie.js' %}"></script>
        <script src="{% static 'mindmap/lib/js/toastr.min.js' %}"></script>
        <script src="{% static 'mindmap/js/common.js' %}"></script>
        <script src="{% static 'mindmap/js/login-register.js' %}"></script>
        <script src="{% static 'mindmap/js/user-menu-popover.js' %}"></script>
        <script src="{% static 'mindmap/js/feedback-dialog.js' %}"></script>
    {% endblock %}
</body>
</html>