mindmap/urls.py
# coding: utf-8
from django.conf.urls import url
from mindmap.views import views_common, views_index, views_mind, views_category, views_user, views_tag
from mindmap.views import views_feedback


urlpatterns = [
    url(r'^$', views_index.index, name='index'),
    url(r'^page/(?P<page>\d+)?$', views_index.index, name='index-without-category'),
    url(r'^category/(?P<category>\d+)/page/(?P<page>\d+)?$', views_index.index, name='index-with-category'),

    # Mind
    url(r'new-mind-page/?', views_mind.mind_new, name='new-mind-page'),
    url(r'new-mind/?', views_mind.process_new_mind, name='new-mind'),
    url(r'mind/delete/?', views_mind.delete_mind, name='mind-delete'),
    url(r'mind/vote/?', views_mind.mind_vote, name='mind-vote'),
    url(r'mind/show/(?P<tid>\d+)?/?', views_mind.show_mind_detail, name='show-mind'),

    # tag
    url(r'mind/tag/(?P<tid>\d+)/page/(?P<page>\d+)?/?', views_tag.show_tag_page, name='mind-tag-page'),

    # 关于
    url(r'about/?', views_common.about_view, name='about'),

    # 反馈
    url(r'feedback/add/?', views_feedback.feedback_add, name='feedback-add'),
]

# 分类
urlpatterns += [
    url(r'category/show/?', views_category.show_category, name='category-show'),
]

# 用户相关url
urlpatterns += [
    # 用户书单列表
    url(r'^user/register/?$', views_user.user_register, name='register'),
    url(r'^user/login/?$', views_user.user_login, name='login'),
    url(r'^user/logout/?$', views_user.user_logout, name='logout'),
    url(r'^user/profile/?$', views_user.user_profile, name='user-profile'),
    url(r'^user/profile/update/?$', views_user.user_profile_update, name='user-profile-update'),
    url(r'^user/page/(?P<page>\d+)/?$', views_user.user_page, name='user-page'),
    url(r'^user/(?P<uid>\d+)/page/(?P<page>\d+)/?$', views_user.user_page, name='user-page-with-uid')
]

# 最后
urlpatterns += [
    # 如果都没有匹配, 返回404页面
    url(r'', views_common.return_404_page, name='404-page'),
]


mindshare/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from mindshare import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mindmap.urls', namespace='mindmap')),
]

templates/mindmap/includes/dialog/_confirm_cancel_modal.html
<div id="confirmCancelModal" class="modal fade bd-example-modal-sm">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="confirmCancelModalTitle" class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="confirmCancelModalText"></p>
            </div>
            <div class="modal-footer">
                <button id="confirmCancelModalConfirm" type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>

templates/mindmap/includes/dialog/_feedback_dialog.html
{# 反馈弹窗 #}

<div id="feedbackModal" class="modal fade bd-example-modal-md">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="feedbackModalTitle" class="modal-title">反馈</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="padding: .3rem .8rem;">
                <textarea id="feedbackContent" style="width: 100%; font-size: .8rem; border: none; outline: none; margin-bottom: -.5rem;" class="no-padding-margin" rows="10" placeholder="请在这里吐槽..." name="description"></textarea>
            </div>
            <div class="modal-footer">
                <button id="feedbackModalConfirm" type="button" class="btn btn-primary" onclick="sendFeedback()">确定</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>

{# 隐藏信息 #}
<span id="feedbackUrl" style="display: none">{% url 'mindmap:feedback-add' %}</span>

templates/mindmap/includes/dialog/_popover_user.html
{# 右上角用户信息弹出框 #}

<div id="userPopoverModal" class="popover-user" style="visibility: hidden;">
    <div class="text-center" style="height: 0;"><i class="fa fa-sort-asc up-arrow" aria-hidden="true"></i></div>
    <div class="menu">
        <a href="{% url 'mindmap:user-page' 1 %}">
            <i class="fa fa-user font-aws-a" aria-hidden="true"></i>
            <span style="padding: 0 5px;">个人中心</span>
        </a>
        <a href="{% url 'mindmap:user-profile' %}">
            <i class="fa fa-cog font-aws-a" aria-hidden="true"></i>
            <span style="padding: 0 5px;">设置</span>
        </a>
        <a href="{% url 'mindmap:logout' %}">
            <i class="fa fa-sign-out font-aws-a" aria-hidden="true"></i>
            <span style="padding: 0 5px;">退出</span>
        </a>
    </div>
</div>